[connections.default]
warehouse = "QUICKSTART_WH"
role = "ACCOUNTADMIN"
database = "QUICKSTART_COMMON"
schema = "PUBLIC"
account = "https://zm23870.ap-southeast-1.snowflakecomputing.com"
user = "Chinmay74"
password = "Chinmay@123"
