[connections.TOWBBEK-PJ40320]
warehouse = "QUICKSTART_WH"
role = "ACCOUNTADMIN"
database = "QUICKSTART_COMMON"
schema = "PUBLIC"
account = "TOWBBEK-PJ40320"
user = "Chinmay74"
password = "Chinmay@123"
